### ISSUE TITLE
Feature request: allow to configure Changelog file regex

### ISSUE THREAD

**Issue by arm4b** [peterjgrainger/action-changelog-reminder#2]
First with GH star here! :star: 

Would be nice to have a changelog file regex configured.

For some repos it's possible to see `CHANGELOG.md`, some may rely on `CHANGES.rst`, `CHANGELOG.rst` and so on.

I'd say this is only missing feature to consume this Github Action in a wild.

----
Also great idea with reminder to add a Changelog! I can finally automate this repeatable routine asking people to add a changelog record for every PR change they contribute.
Nit: Alternative way is to have this as CI check, as seen at https://github.com/marketplace/pr-milestone-check, but bot Comment is nice too.

**Comment by peterjgrainger** [comment]
Thanks @armab. As you can probably tell by the check, I made it for our specific use case :) 

I was going to make it configurable but wanted to check that it was usable for someone else before I spent any more time on it and it is!

Should be straight forward to add an input but might make it a glob instead of regex. 

If I don't get around to it I'll try to get a contributor in hacktoberfest
